import "dotenv/config";
import mongoose from "mongoose";
import Subject from "../models/Subject.js";

const questions = [
  { question: "What is a process in an operating system?", options: ["A program stored on disk","A program in execution","A file in memory","A CPU register set"], correct: 1, explanation: "A process is a program in execution. It includes the program code, current activity, and associated resources like memory and open files.", topic: "Process Management", difficulty: "Easy" },
  { question: "Which data structure does the OS use to store all information about a process?", options: ["Page Table","File Control Block","Process Control Block (PCB)","Segment Table"], correct: 2, explanation: "The PCB (Process Control Block) stores all information about a process including PID, state, program counter, registers, memory limits, and open files.", topic: "Process Management", difficulty: "Easy" },
  { question: "How many states are there in the standard 5-state process model?", options: ["3","4","5","6"], correct: 2, explanation: "The 5-state model includes: New, Ready, Running, Waiting (Blocked), and Terminated.", topic: "Process Management", difficulty: "Easy" },
  { question: "A process moves from Running to Waiting. What is the most likely cause?", options: ["Timer interrupt","Higher priority process arrives","Process requests I/O","Process calls fork()"], correct: 2, explanation: "Running → Waiting occurs when a process requests I/O or waits for an event. Timer interrupt causes Running → Ready (preemption).", topic: "Process Management", difficulty: "Medium" },
  { question: "Which transition in the process state model is caused by preemption?", options: ["New → Ready","Running → Waiting","Running → Ready","Waiting → Ready"], correct: 2, explanation: "Preemption causes Running → Ready. The OS forcibly removes the CPU from the running process (e.g., timer interrupt or higher-priority arrival).", topic: "Process Management", difficulty: "Medium" },
  { question: "What is saved in the PCB during a context switch?", options: ["Only the Process ID","Program Counter and CPU Registers","Open file list only","Memory pages"], correct: 1, explanation: "During context switch, the CPU context (Program Counter + all registers) is saved into the PCB so the process can resume exactly where it left off.", topic: "Process Management", difficulty: "Medium" },
  { question: "Which field in PCB helps resume a process at the correct instruction?", options: ["Process ID","Process State","Program Counter","Base Register"], correct: 2, explanation: "The Program Counter stores the address of the next instruction. When context switching back, the OS loads the saved PC into the CPU.", topic: "Process Management", difficulty: "Easy" },
  { question: "What is the purpose of the 'Process State' field in PCB?", options: ["Store memory address","Track current state (Ready/Running/Waiting)","Count open files","Store priority value"], correct: 1, explanation: "The Process State field records the current state of the process so the OS scheduler knows which processes are eligible for CPU allocation.", topic: "Process Management", difficulty: "Easy" },
  { question: "Which of the following is NOT stored in the PCB?", options: ["Program Counter","CPU Registers","Actual program code","Open file list"], correct: 2, explanation: "The actual program code (text segment) is stored in the process's memory space, not in the PCB. PCB stores metadata about the process.", topic: "Process Management", difficulty: "Medium" },
  { question: "What happens to a process's PCB when the process terminates?", options: ["PCB is saved to disk","PCB is deallocated by the OS","PCB is moved to ready queue","PCB remains forever"], correct: 1, explanation: "When a process terminates, the OS deallocates (frees) its PCB after releasing all resources. The process entry is removed from the process table.", topic: "Process Management", difficulty: "Easy" },
  { question: "The system call used to create a new process in Unix/Linux is:", options: ["exec()","wait()","fork()","spawn()"], correct: 2, explanation: "fork() creates a new process (child) that is a copy of the calling process (parent). The child gets a new PID but inherits the parent's code, data, and open files.", topic: "Process Management", difficulty: "Easy" },
  { question: "After fork(), the child process:", options: ["Starts from main()","Continues from where fork() returned","Starts a new program","Terminates immediately"], correct: 1, explanation: "After fork(), both parent and child continue execution from the line after fork(). The child is an exact copy of the parent at that moment.", topic: "Process Management", difficulty: "Medium" },
  { question: "What does the exec() system call do?", options: ["Creates a new process","Replaces current process image with a new program","Terminates the process","Waits for child process"], correct: 1, explanation: "exec() replaces the current process's memory image with a new program. The PID remains the same but the code, data, and stack are replaced.", topic: "Process Management", difficulty: "Medium" },
  { question: "What is a zombie process?", options: ["Process waiting for I/O","Process that has finished but its PCB still exists","Process with no parent","Process in infinite loop"], correct: 1, explanation: "A zombie process has completed execution but its PCB remains in the process table because the parent hasn't called wait() to collect its exit status.", topic: "Process Management", difficulty: "Medium" },
  { question: "What is an orphan process?", options: ["Process with no children","Process whose parent has terminated","Process waiting for CPU","Process in New state"], correct: 1, explanation: "An orphan process is one whose parent has terminated. In Unix, orphan processes are adopted by the init process (PID 1).", topic: "Process Management", difficulty: "Medium" },
  { question: "Which system call does a parent use to wait for a child process to finish?", options: ["fork()","exec()","wait()","kill()"], correct: 2, explanation: "wait() suspends the parent until one of its child processes terminates. It also retrieves the child's exit status and cleans up the zombie.", topic: "Process Management", difficulty: "Easy" },
  { question: "The Process ID (PID) is:", options: ["Same for parent and child after fork()","A unique integer assigned to each process","Stored in CPU registers","Assigned by the programmer"], correct: 1, explanation: "PID is a unique non-negative integer assigned by the OS to each process. No two running processes can have the same PID.", topic: "Process Management", difficulty: "Easy" },
  { question: "In the 5-state process model, from which state can a process NOT directly go to Running?", options: ["Ready","Waiting","New","Both Waiting and New"], correct: 3, explanation: "Only the Ready state can transition directly to Running (via dispatch). A process in Waiting or New must first move to Ready before getting CPU time.", topic: "Process Management", difficulty: "Hard" },
  { question: "What is process scheduling?", options: ["Allocating memory to processes","Deciding which process gets CPU next","Managing file access","Handling I/O requests"], correct: 1, explanation: "Process scheduling is the OS mechanism that decides which process in the Ready queue gets allocated the CPU next, based on a scheduling algorithm.", topic: "Process Management", difficulty: "Easy" },
  { question: "The component of the OS responsible for selecting the next process to run is called:", options: ["Memory Manager","Short-term Scheduler (CPU Scheduler)","I/O Manager","File System"], correct: 1, explanation: "The short-term scheduler (CPU scheduler) selects from the Ready queue and dispatches a process to the CPU. It runs very frequently (milliseconds).", topic: "Process Management", difficulty: "Easy" },
  { question: "What is the degree of multiprogramming?", options: ["Number of CPUs in the system","Number of processes in memory at one time","Number of threads per process","Number of I/O devices"], correct: 1, explanation: "The degree of multiprogramming refers to the number of processes simultaneously kept in memory. Higher degree = better CPU utilization.", topic: "Process Management", difficulty: "Medium" },
  { question: "Which of the following causes a transition from Waiting to Ready?", options: ["Timer interrupt","I/O completion","Process exit","Higher priority process arrives"], correct: 1, explanation: "When the I/O operation (or event) that the process was waiting for completes, the OS moves the process from Waiting back to the Ready queue.", topic: "Process Management", difficulty: "Medium" },
  { question: "A process in the New state is:", options: ["Currently executing on CPU","Waiting for I/O","Being created and not yet admitted","Waiting in ready queue"], correct: 2, explanation: "A process in the New state has been created (PCB exists) but has not yet been admitted to the Ready queue by the long-term scheduler.", topic: "Process Management", difficulty: "Easy" },
  { question: "What is the role of the long-term scheduler?", options: ["Selects which ready process gets CPU","Controls degree of multiprogramming","Manages page faults","Handles context switches"], correct: 1, explanation: "The long-term scheduler decides which processes from the job pool are admitted into memory (New → Ready). It controls the degree of multiprogramming.", topic: "Process Management", difficulty: "Medium" },
  { question: "Context switching overhead is considered:", options: ["Useful CPU time","Wasted/overhead time (no useful work done)","I/O time","Memory allocation time"], correct: 1, explanation: "During context switch, the CPU saves/restores process state but does no useful work. It is pure overhead. Faster context switches = better performance.", topic: "Process Management", difficulty: "Medium" },
  { question: "Which of the following is true about threads vs processes?", options: ["Threads have separate memory spaces","Threads within same process share memory","Each thread has its own PCB","Threads cannot share files"], correct: 1, explanation: "Threads within the same process share the process's address space, code, data, and open files. Each thread has its own stack and registers only.", topic: "Process Management", difficulty: "Medium" },
  { question: "A thread has its own:", options: ["Heap memory","Code segment","Stack and registers","Open file table"], correct: 2, explanation: "Each thread has its own stack (for local variables and function calls) and register set (including PC). Heap, code, and data are shared among threads of the same process.", topic: "Process Management", difficulty: "Medium" },
  { question: "What is the main advantage of threads over processes?", options: ["Better security isolation","Lower creation and communication overhead","More memory allocation","Better I/O performance"], correct: 1, explanation: "Thread creation is much cheaper than process creation since threads share memory. Communication between threads (shared memory) is also faster than IPC between processes.", topic: "Process Management", difficulty: "Medium" },
  { question: "User-level threads are managed by:", options: ["OS kernel","User-space thread library","CPU hardware","Memory manager"], correct: 1, explanation: "User-level threads are managed entirely by a user-space library (like POSIX pthreads). The kernel sees only the process, not individual threads.", topic: "Process Management", difficulty: "Medium" },
  { question: "A disadvantage of user-level threads is:", options: ["High creation cost","If one thread blocks on I/O, all threads in the process block","Cannot share data","Require separate PCBs"], correct: 1, explanation: "Since the kernel doesn't know about user-level threads, if one makes a blocking I/O call, the kernel blocks the entire process, starving other threads.", topic: "Process Management", difficulty: "Hard" },
  { question: "Kernel-level threads are managed by:", options: ["User libraries","The OS kernel","The process itself","Hardware thread units"], correct: 1, explanation: "Kernel-level threads are created and managed by the OS. The kernel schedules each thread independently, so one blocking thread doesn't block others.", topic: "Process Management", difficulty: "Medium" },
  { question: "Which of the following is an example of IPC (Inter-Process Communication)?", options: ["Thread creation","fork()","Shared memory and pipes","Context switching"], correct: 2, explanation: "IPC mechanisms allow processes to communicate: shared memory, pipes, message queues, semaphores, and sockets are all IPC mechanisms.", topic: "Process Management", difficulty: "Easy" },
  { question: "In shared memory IPC, which process sets up the shared memory segment?", options: ["Always the parent","Always the child","Any process — typically the first to request it","The OS kernel automatically"], correct: 2, explanation: "Either process can create the shared memory segment using shmget(). Other processes attach to it using shmat(). The creating process typically sets it up first.", topic: "Process Management", difficulty: "Hard" },
  { question: "Pipes in Unix are:", options: ["Bidirectional by default","Unidirectional — data flows one way","Only for threads","Persistent across reboots"], correct: 1, explanation: "Anonymous pipes are unidirectional. Data written to the write end can only be read from the read end. For bidirectional communication, two pipes are needed.", topic: "Process Management", difficulty: "Medium" },
  { question: "What is a named pipe (FIFO) in Unix?", options: ["A pipe between threads","A pipe with a file system entry allowing unrelated processes to communicate","A bidirectional pipe","A pipe in kernel memory only"], correct: 1, explanation: "Named pipes (FIFOs) have a pathname in the file system, allowing unrelated processes (not just parent-child) to communicate through the pipe.", topic: "Process Management", difficulty: "Hard" },
  { question: "What is the init process in Linux?", options: ["First process created by the kernel (PID 1)","Process that initializes hardware","Process that manages memory","Process that handles I/O"], correct: 0, explanation: "init (or systemd) is the first user-space process created by the kernel with PID 1. It is the ancestor of all other processes and adopts orphan processes.", topic: "Process Management", difficulty: "Easy" },
  { question: "Process synchronization is needed when:", options: ["Processes run sequentially","Multiple processes access shared data concurrently","A single process runs","Processes do only I/O"], correct: 1, explanation: "When multiple processes/threads access shared data concurrently and at least one writes, synchronization is needed to prevent race conditions and ensure data consistency.", topic: "Process Management", difficulty: "Easy" },
  { question: "A race condition occurs when:", options: ["Process runs too fast","Two processes race to finish first","Output depends on timing/order of concurrent accesses","Process waits too long"], correct: 2, explanation: "A race condition occurs when multiple processes access shared data and the final result depends on the order/timing of execution, leading to unpredictable outcomes.", topic: "Process Management", difficulty: "Medium" },
  { question: "What is the Critical Section?", options: ["The most important code in a program","A code segment where shared resources are accessed","The section that causes page faults","The CPU scheduling code"], correct: 1, explanation: "The Critical Section is the part of code where a process accesses shared resources. Only one process should execute its CS at a time.", topic: "Process Management", difficulty: "Medium" },
  { question: "The three requirements for a Critical Section solution are:", options: ["Speed, Fairness, Priority","Mutual Exclusion, Progress, Bounded Waiting","Atomicity, Consistency, Isolation","Lock, Unlock, Wait"], correct: 1, explanation: "Mutual Exclusion (only one in CS at a time), Progress (decision in finite time), and Bounded Waiting (no starvation).", topic: "Process Management", difficulty: "Medium" },
  { question: "Peterson's solution works for how many processes?", options: ["1","2","Any number","Only 3"], correct: 1, explanation: "Peterson's solution is a software-based solution for the Critical Section problem for exactly 2 processes.", topic: "Process Management", difficulty: "Medium" },
  { question: "A binary semaphore can take values:", options: ["0 to infinity","0 and 1 only","-1 to 1","0 to 255"], correct: 1, explanation: "A binary semaphore (mutex) can only take values 0 (locked) or 1 (unlocked). It is used for mutual exclusion.", topic: "Process Management", difficulty: "Easy" },
  { question: "A counting semaphore is used for:", options: ["Mutual exclusion only","Managing a resource with multiple instances","Process creation","Memory allocation"], correct: 1, explanation: "A counting semaphore tracks the count of available resource instances. It can range from 0 to N.", topic: "Process Management", difficulty: "Medium" },
  { question: "The wait() operation on a semaphore S:", options: ["Increments S and signals waiting processes","Decrements S; if S < 0, process blocks","Resets S to 0","Does nothing if S > 0"], correct: 1, explanation: "wait(S) [P(S)] decrements S. If S becomes negative, the calling process blocks.", topic: "Process Management", difficulty: "Medium" },
  { question: "The signal() operation on a semaphore S:", options: ["Decrements S","Sets S to 1","Increments S; wakes up a waiting process if any","Resets S to 0"], correct: 2, explanation: "signal(S) [V(S)] increments S. If there are blocked processes, one is woken up.", topic: "Process Management", difficulty: "Medium" },
  { question: "A monitor differs from a semaphore in that:", options: ["Monitors are slower","Monitors provide higher-level synchronization with automatic mutual exclusion","Monitors use more memory","Monitors are hardware-based"], correct: 1, explanation: "A monitor is a high-level synchronization construct. Mutual exclusion is automatic — only one process can be active inside the monitor at a time.", topic: "Process Management", difficulty: "Hard" },
  { question: "In the Producer-Consumer problem using semaphores, the semaphore 'full' is initialized to:", options: ["Buffer size N","0","1","-1"], correct: 1, explanation: "'full' counts filled buffer slots and starts at 0 (buffer is empty initially).", topic: "Process Management", difficulty: "Hard" },
  { question: "What is a deadlock?", options: ["Process taking too much CPU","Set of processes each waiting for resources held by others indefinitely","Process with highest priority","I/O bottleneck"], correct: 1, explanation: "Deadlock is a situation where a set of processes are permanently blocked because each waits for a resource held by another.", topic: "Process Management", difficulty: "Easy" },
  { question: "How many Coffman conditions are necessary for deadlock?", options: ["2","3","4","5"], correct: 2, explanation: "There are exactly 4 Coffman conditions: Mutual Exclusion, Hold and Wait, No Preemption, and Circular Wait.", topic: "Process Management", difficulty: "Medium" },
  { question: "Which Coffman condition states that a resource can only be held by one process at a time?", options: ["Hold and Wait","No Preemption","Mutual Exclusion","Circular Wait"], correct: 2, explanation: "Mutual Exclusion means only one process can use a resource at a time.", topic: "Process Management", difficulty: "Easy" },
  { question: "The Banker's Algorithm is used for:", options: ["Deadlock detection","Deadlock avoidance","Deadlock prevention","Deadlock recovery"], correct: 1, explanation: "The Banker's Algorithm (by Dijkstra) is a deadlock avoidance algorithm that checks if granting a request keeps the system in a safe state.", topic: "Process Management", difficulty: "Medium" },
  { question: "A system is in a 'safe state' if:", options: ["No process is in Waiting state","There exists a safe sequence of process execution","All resources are free","No deadlock has occurred yet"], correct: 1, explanation: "A safe state means there exists at least one sequence where all processes can complete using available resources.", topic: "Process Management", difficulty: "Medium" },
  { question: "In a Resource Allocation Graph (RAG), a cycle:", options: ["Always indicates deadlock","Indicates deadlock only if each resource type has single instance","Is impossible","Means process will finish soon"], correct: 1, explanation: "In a RAG, a cycle with single-instance resources definitively means deadlock. With multi-instance resources, it is necessary but not sufficient.", topic: "Process Management", difficulty: "Hard" },
  { question: "Deadlock prevention works by:", options: ["Detecting deadlock after it occurs","Ensuring at least one Coffman condition never holds","Killing processes when deadlock is detected","Running processes sequentially"], correct: 1, explanation: "Deadlock prevention ensures that at least one of the four Coffman conditions can never hold simultaneously.", topic: "Process Management", difficulty: "Medium" },
  { question: "Which of the following eliminates the 'Hold and Wait' condition?", options: ["Allow preemption of resources","Require process to request all resources at once before starting","Assign resource ordering","Use semaphores"], correct: 1, explanation: "Requiring a process to request ALL resources before execution begins eliminates Hold and Wait.", topic: "Process Management", difficulty: "Hard" },
  { question: "Process starvation means:", options: ["Process uses too much memory","Process is ready but never gets CPU for a very long time","Process terminates unexpectedly","Process creates too many children"], correct: 1, explanation: "Starvation occurs when a process in the Ready queue is indefinitely denied CPU because other processes keep getting priority.", topic: "Process Management", difficulty: "Medium" },
  { question: "What is the difference between starvation and deadlock?", options: ["No difference","In deadlock, processes are blocked waiting for each other; in starvation, a process is always bypassed by others","Starvation requires 4 Coffman conditions","Deadlock is recoverable, starvation is not"], correct: 1, explanation: "Deadlock requires circular wait. Starvation means a process keeps getting bypassed but could theoretically run.", topic: "Process Management", difficulty: "Hard" },
  { question: "CPU-bound processes spend most of their time:", options: ["Waiting for I/O","Doing computations on CPU","In the Waiting state","Creating child processes"], correct: 1, explanation: "CPU-bound processes primarily perform computation and rarely do I/O. Examples: matrix multiplication, scientific simulations.", topic: "Process Management", difficulty: "Easy" },
  { question: "I/O-bound processes are characterized by:", options: ["Long CPU bursts","Short CPU bursts with frequent I/O requests","No I/O operations","High memory usage"], correct: 1, explanation: "I/O-bound processes frequently request I/O, so they have short CPU bursts. Examples: text editors, database queries.", topic: "Process Management", difficulty: "Easy" },
  { question: "The short-term scheduler runs:", options: ["Once when system boots","Every few hundred milliseconds","Only when a process terminates","Once per minute"], correct: 1, explanation: "The short-term (CPU) scheduler runs very frequently — typically every few milliseconds — to decide which Ready process gets the CPU next.", topic: "Process Management", difficulty: "Medium" },
  { question: "The medium-term scheduler is responsible for:", options: ["Deciding which process runs next on CPU","Swapping processes in and out of memory","Admitting new jobs","Handling I/O interrupts"], correct: 1, explanation: "The medium-term scheduler swaps processes out of memory to disk and back to manage the degree of multiprogramming.", topic: "Process Management", difficulty: "Medium" },
  { question: "Process swapping is performed by:", options: ["Short-term scheduler","Long-term scheduler","Medium-term scheduler","I/O scheduler"], correct: 2, explanation: "The medium-term scheduler performs swapping — moving processes between main memory and secondary storage.", topic: "Process Management", difficulty: "Medium" },
  { question: "In process creation using fork(), the return value in the parent process is:", options: ["0","-1 on failure, 0 on success","The PID of the child process","The PID of the parent process"], correct: 2, explanation: "fork() returns the child's PID to the parent, returns 0 to the child, and returns -1 if fork fails.", topic: "Process Management", difficulty: "Medium" },
  { question: "What is copy-on-write (COW) optimization in fork()?", options: ["Child immediately copies all parent pages","Parent and child share pages until one modifies them, then copy is made","All pages are copied before fork returns","Only code pages are shared"], correct: 1, explanation: "COW delays page copying — parent and child initially share the same physical pages. A copy is made only when either process writes.", topic: "Process Management", difficulty: "Hard" },
  { question: "Which signal is sent to a process when Ctrl+C is pressed?", options: ["SIGKILL","SIGTERM","SIGINT","SIGHUP"], correct: 2, explanation: "Ctrl+C sends SIGINT (Signal Interrupt, signal 2) to the foreground process. The default action is termination.", topic: "Process Management", difficulty: "Medium" },
  { question: "SIGKILL (signal 9) differs from SIGTERM in that:", options: ["SIGKILL is weaker","SIGKILL cannot be caught, blocked, or ignored","SIGTERM kills immediately","SIGKILL sends a message to the process"], correct: 1, explanation: "SIGKILL (9) forcibly terminates a process and cannot be caught, blocked, or ignored. SIGTERM (15) can be handled gracefully.", topic: "Process Management", difficulty: "Medium" },
  { question: "What is the process table in an OS?", options: ["A table in secondary storage","An OS data structure containing PCBs of all processes","A table of memory addresses","A CPU cache"], correct: 1, explanation: "The process table is an OS data structure (array or list) that holds the PCB of every process in the system.", topic: "Process Management", difficulty: "Easy" },
  { question: "Multithreading models describe:", options: ["How memory is allocated to threads","How user-level threads map to kernel-level threads","How processes are scheduled","How I/O is handled by threads"], correct: 1, explanation: "Multithreading models describe the mapping between user-level threads and kernel-level threads.", topic: "Process Management", difficulty: "Medium" },
  { question: "In the Many-to-One threading model:", options: ["Each user thread maps to one kernel thread","Many user threads map to one kernel thread","Many kernel threads map to one user thread","All threads run in parallel on multiple CPUs"], correct: 1, explanation: "Many-to-One: multiple user threads map to a single kernel thread. Disadvantage: if one blocks, all block.", topic: "Process Management", difficulty: "Hard" },
  { question: "In the One-to-One threading model (used in Linux/Windows):", options: ["One user thread maps to many kernel threads","Each user thread maps to exactly one kernel thread","One process has one thread","Threads share a single kernel thread"], correct: 1, explanation: "One-to-One maps each user thread to a kernel thread. Advantage: true parallelism. Used in Linux (pthreads) and Windows.", topic: "Process Management", difficulty: "Medium" },
  { question: "A process can be terminated by:", options: ["Only itself (normal exit)","Another process using kill(), OS due to errors, or itself","Only the OS","Only the parent process"], correct: 1, explanation: "A process can terminate by: normal exit(), killed by kill() system call, or OS termination on fatal error.", topic: "Process Management", difficulty: "Medium" },
  { question: "What does 'nice value' represent in Linux process scheduling?", options: ["Process memory usage","Process scheduling priority hint","Number of threads","CPU burst length"], correct: 1, explanation: "The nice value (-20 to +19) is a hint to the scheduler about priority. A lower value = higher priority.", topic: "Process Management", difficulty: "Medium" },
  { question: "The 'ps' command in Linux shows:", options: ["Power status","Process status — list of running processes","Partition sizes","Printer status"], correct: 1, explanation: "'ps' shows a snapshot of current processes. 'ps aux' shows all processes with CPU/memory usage.", topic: "Process Management", difficulty: "Easy" },
  { question: "What is a daemon process?", options: ["A process with root privileges","A background process that runs continuously providing a service","A process that creates many children","A zombie process that never dies"], correct: 1, explanation: "A daemon is a background process (typically started at boot) that provides a service like httpd, sshd, or cron.", topic: "Process Management", difficulty: "Medium" },
  { question: "Process migration in distributed systems refers to:", options: ["Moving files between processes","Moving a running process from one machine to another","Copying process code","Thread scheduling"], correct: 1, explanation: "Process migration moves a process from one node to another in a distributed system, often for load balancing.", topic: "Process Management", difficulty: "Hard" },
  { question: "What is the purpose of the 'wait()' system call?", options: ["Make process sleep for specified time","Parent waits for child to terminate and collects exit status","Wait for I/O completion","Wait for memory allocation"], correct: 1, explanation: "wait() blocks the parent until any child terminates. It returns the PID and exit status and cleans up the zombie.", topic: "Process Management", difficulty: "Easy" },
  { question: "If a parent process exits before its children, the children become:", options: ["Zombie processes","Orphan processes","Daemon processes","Terminated processes"], correct: 1, explanation: "Children whose parent terminates become orphan processes. In Linux, init (PID 1) adopts all orphans.", topic: "Process Management", difficulty: "Medium" },
  { question: "How is a zombie process removed from the system?", options: ["Kill signal sent to zombie","Parent calls wait() to collect exit status","Zombie removes itself after timeout","OS removes it after 60 seconds"], correct: 1, explanation: "A zombie is removed when the parent calls wait(), collecting the child's exit status. The OS then deallocates the PCB.", topic: "Process Management", difficulty: "Medium" },
  { question: "POSIX thread (pthread) creation uses which function?", options: ["fork()","thread_create()","pthread_create()","CreateThread()"], correct: 2, explanation: "pthread_create() creates a new POSIX thread. It takes thread ID, attributes, the function to run, and its argument.", topic: "Process Management", difficulty: "Medium" },
  { question: "Thread synchronization using mutex in pthreads uses:", options: ["sem_wait() and sem_post()","pthread_mutex_lock() and pthread_mutex_unlock()","pthread_join()","wait() and signal()"], correct: 1, explanation: "pthread_mutex_lock() acquires the mutex (blocks if locked), and pthread_mutex_unlock() releases it.", topic: "Process Management", difficulty: "Medium" },
  { question: "What happens when pthread_join() is called?", options: ["Creates a new thread","Calling thread waits for specified thread to terminate","Kills the specified thread","Detaches thread from process"], correct: 1, explanation: "pthread_join() blocks the calling thread until the specified thread terminates and retrieves its return value.", topic: "Process Management", difficulty: "Medium" },
  { question: "In the Dining Philosophers problem, deadlock occurs when:", options: ["One philosopher eats too much","All philosophers pick up their left fork simultaneously","A philosopher never gets hungry","Two philosophers share a fork"], correct: 1, explanation: "If all 5 philosophers pick up their left fork simultaneously, each waits for the right fork — classic deadlock (circular wait).", topic: "Process Management", difficulty: "Hard" },
  { question: "One solution to the Dining Philosophers deadlock is:", options: ["Use only 4 forks","Allow at most N-1 philosophers to sit simultaneously","Make philosophers eat faster","Remove one philosopher"], correct: 1, explanation: "Allowing at most N-1 philosophers at the table simultaneously breaks circular wait. At least one can always eat.", topic: "Process Management", difficulty: "Hard" },
  { question: "In the Reader-Writer problem, which condition must hold for consistency?", options: ["Only one reader at a time","Multiple readers can read simultaneously, but writers need exclusive access","Writers can write while readers read","Only writers can access the resource"], correct: 1, explanation: "Multiple readers can read concurrently (no conflict). A writer needs exclusive access — no readers or writers can access while a writer writes.", topic: "Process Management", difficulty: "Hard" },
  { question: "What is priority inversion?", options: ["Low-priority process runs before high-priority","High-priority process is blocked because a low-priority process holds a needed resource","Scheduling queue is reversed","Priorities are assigned incorrectly"], correct: 1, explanation: "Priority inversion: High-priority process H waits for a resource held by low-priority process L, which is preempted by medium-priority M.", topic: "Process Management", difficulty: "Hard" },
  { question: "Priority inheritance protocol solves priority inversion by:", options: ["Removing low-priority process","Temporarily raising the priority of the resource-holding process","Blocking medium-priority processes","Ignoring priority during resource access"], correct: 1, explanation: "Priority inheritance: when L holds a resource needed by H, L temporarily inherits H's priority, preventing preemption by M.", topic: "Process Management", difficulty: "Hard" },
  { question: "Which of the following scheduling algorithms can cause starvation?", options: ["Round Robin","FCFS","Priority Scheduling","All of the above"], correct: 2, explanation: "Priority Scheduling can cause starvation — low-priority processes may never run if high-priority ones keep arriving.", topic: "Process Management", difficulty: "Medium" },
  { question: "Aging is a technique used to:", options: ["Remove old processes","Gradually increase priority of waiting processes to prevent starvation","Measure process age","Reduce memory of old processes"], correct: 1, explanation: "Aging gradually increases the priority of processes that have been waiting long. This prevents starvation.", topic: "Process Management", difficulty: "Medium" },
  { question: "A process control block is also known as:", options: ["Page Table Entry","Task Control Block or Process Descriptor","File Control Block","Interrupt Descriptor"], correct: 1, explanation: "PCB is also called Task Control Block (TCB) or process descriptor (Linux: struct task_struct).", topic: "Process Management", difficulty: "Easy" },
  { question: "The 'fork bomb' is:", options: ["A process that fills disk","A process that recursively creates copies of itself until system resources are exhausted","A virus that corrupts fork() syscall","A process with many threads"], correct: 1, explanation: "A fork bomb recursively creates copies of itself, creating exponentially many processes until the system crashes.", topic: "Process Management", difficulty: "Hard" },
  { question: "ulimit command in Linux is used to:", options: ["Show CPU usage","Set limits on resources a process can use (max processes, file size, memory)","Update system libraries","List all users"], correct: 1, explanation: "ulimit sets resource limits for processes: max number of processes, max file size, max stack size, max memory, etc.", topic: "Process Management", difficulty: "Medium" },
  { question: "In a multiprocessor system, process affinity means:", options: ["Process prefers certain I/O devices","Tendency to keep a process running on the same processor (cache warm)","Process cannot be migrated","Process priority on specific CPU"], correct: 1, explanation: "Processor affinity keeps a process running on the same CPU core to benefit from warm cache. Migration to another CPU requires cache reload.", topic: "Process Management", difficulty: "Hard" },
  { question: "Load balancing in multiprocessor scheduling:", options: ["Balances memory usage","Distributes processes across CPUs to keep all busy","Balances I/O load","Prioritizes processes equally"], correct: 1, explanation: "Load balancing distributes processes/threads across available CPUs to maximize utilization.", topic: "Process Management", difficulty: "Medium" },
  { question: "What is a lightweight process (LWP)?", options: ["Process with minimal memory","Intermediate between user thread and kernel thread","Process with low priority","A thread that uses less CPU"], correct: 1, explanation: "An LWP is a kernel-supported entity that acts as a bridge between user-level threads and kernel threads.", topic: "Process Management", difficulty: "Hard" },
  { question: "What is the main difference between concurrency and parallelism?", options: ["No difference","Concurrency: multiple tasks making progress (may interleave); Parallelism: multiple tasks executing simultaneously on multiple CPUs","Parallelism is sequential","Concurrency requires multiple CPUs"], correct: 1, explanation: "Concurrency: dealing with multiple tasks at once (can interleave on a single CPU). Parallelism: physically executing simultaneously on multiple CPU cores.", topic: "Process Management", difficulty: "Medium" },
  { question: "In a uniprocessor system, parallelism is:", options: ["Fully achievable","Not achievable — only concurrency through interleaving","Achieved through hyper-threading","Achieved through virtual memory"], correct: 1, explanation: "True parallelism requires multiple processors. A uniprocessor can only simulate concurrency by switching between processes.", topic: "Process Management", difficulty: "Medium" },
  { question: "Process isolation means:", options: ["Processes cannot communicate","Each process has its own protected address space — one process cannot access another's memory","Processes run one at a time","Processes are sorted by priority"], correct: 1, explanation: "Process isolation: each process has its own virtual address space. The OS and MMU prevent a process from reading/writing another's memory.", topic: "Process Management", difficulty: "Easy" },
  { question: "What is the role of the dispatcher in process scheduling?", options: ["Selects which process to run","Gives CPU to the selected process — performs context switch, mode switch, jumps to correct location","Manages memory for processes","Handles I/O for processes"], correct: 1, explanation: "The dispatcher handles the mechanics of context switching: saves current state, loads selected process state, switches to user mode, and jumps to the correct PC.", topic: "Process Management", difficulty: "Medium" },
  { question: "Dispatch latency is the time taken to:", options: ["Select a process for execution","Stop current process and start another — the overhead of context switching","Complete an I/O operation","Create a new process"], correct: 1, explanation: "Dispatch latency is the time from when the scheduler selects a process to when it actually starts running. It should be minimized.", topic: "Process Management", difficulty: "Medium" },
  { question: "Which of the following is true about the 'exec()' family of system calls?", options: ["exec() creates a new process with a new PID","exec() replaces the calling process image with a new program — same PID","exec() duplicates the process like fork()","exec() can only be called after fork()"], correct: 1, explanation: "exec() replaces the current process's memory with a new program. The PID remains the same. Typically used after fork().", topic: "Process Management", difficulty: "Medium" },
];

async function importQuestions() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("Connected to MongoDB...");

    const result = await Subject.updateOne(
      { id: "os" },
      { $push: { questions: { $each: questions } } }
    );

    console.log(`✅ Added ${questions.length} Process Management questions to OS subject!`);
    console.log(`   Matched: ${result.matchedCount}, Modified: ${result.modifiedCount}`);
  } catch (err) {
    console.error("❌ Error:", err.message);
  } finally {
    await mongoose.disconnect();
    process.exit(0);
  }
}

importQuestions();
